# Generated by Django 6.1 on 2026-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[(0, 'none'), (1, 'low'), (2, 'medium'), (3, 'high'), (4, 'urgent')], default=0, max_length=10)),
            ],
        ),
    ]
